sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Ox+iJzlp9kolHgFvkBzY2UIwtBTv6CKwOPIUlBcomB98CRP8iSpe0Z4HAhn9isaNYk+l7F2quN2zzYspitD7gSacuRmRdYmKTpe5KChz+gf+dxpAYCWXs5LWLEWyuUrZTznUOWrRQEd0p7MfZfR5vTLDP49DIns1/2sYFOKTSkUGkbU2o9geuBUemPlq+y072JYzTMKWOw/20MzUn0b07V7be7YBNGWDAd5CGVFhCaiRa3V3VtkEr9tL4v3b58XeTmJ5NW6irvmqFFS/ermJu0hCs6pLa9X/hjPQARlRx7RuCSrtaPU/5BDGrmC0UIyegAoy0UZCOVvMG+fGuWQf1HF2rcpK4A2cM8xvga0esqjNS8xoGSpO5x8MXlsE6a9OpiTWJ/9Crbv+AfV5rhp2pgvIZXJbl/Isfrd49SR2BR4aUIHbqnJtregxMvsdkn61k/WJVKAjx8WDmHYa01/IpQ5yRj/S573SVdhvNnk+mBrTIIKyqdqiXVKciJKPtNWkHBMTaxJzY8aXUusorIORzGrhVxOKuRowoFPtP1jknnFbqp3pYqcrwmgPk0d0p6JfkvesUOUfI6onh5VgHDKx/nf6VDV4EOowNCBv6afZJS6bbxM8QeuDLkk3zYAYlpNSnmcU4vXVHz1+GIacB1r3dHbVKXXXZ0q71FdC8Ec+wcE=
  - secure: sNVDH+c9oECUBhXkDgYgQyfOpqtpYQIcst/9zXJtUMnJvCEOpkK+3CrlJNhwTW4dcewiOWlGhCm0AEgZOVTtOt/CuIoHZAYKY/RRDLhrTtpoLr6gkwtf5AeD5PjnKHINTP+AS08OYrP0CDDbt0MK8/5bhTLhfUXzojye7PB+PH+eQBj9jHrwiq5XJNZWEPxNuymL28veTN373l3lsld0j5GmWQviyyvwrruUHikPZ+2Y9lwfwfOTW6zaNkfIWYiVW78PfAAVSXWvcGL5j7wSMM5KmykY4l47Q7vUPBnEZQ/6ptABGBGxCWAapdhRLt45H9nGtzRuWuxsgS63AIblqEhJzp+tOnhRkrvwnzOwu1JNepYGiwY3hWPIA+epnv5+1obYE/AQ8MDyRFQsnRgRbffn1OHWobZjRgOFNWq1mRuXoLdzN3b9skgWhp7sLgViTe1zU+7JR9RpJQNHHfLlo4GYkB/ElMMmEkiK6iAzQdNUMObX7iZVSFaemtGHhn3u4BnBGAzIRySduQeOwHsuK6KJjdct5ZuKKdcyQV2EiMq1WNr3Nw1yzctGzuBQfKro5OOoxyopqpwAavyue2T3baXpuxXNbeqQs3tRznd4rDjie1vAUn1blhn6M2gUH1UQkarRBpjIOjJJRNfDs5H9cy4+mQGaItXpdBLteHgcO1I=
  - secure: a9MTBa+5FZ1xpMmMh80BEPAQ4+ulX0ImBRW92011qctms6qmJ1HNte7aM08MfcWPKXevgnYAsFJzk4rpuWwWfvyCmKilMTzhGRDu3jjDuUxOzweOHa7IL3e+2p3RCPVMROSFS8emf1bRV6I97ocu+zCATuT5OA2NpdLJ6HBZkMDDc3QQvUWRUm2H6pR83YrQNKhg+oINHxBCdyx/pqcYWgi53LUTmYcYa0+M/y99sBqToaa8rCS2qsNJIaiFTUH2Se/DMRJfySwWsm/ikD+P41oidIXpM8XdJPuJV6jYwssDxGBBF/t414BiSGUUH3rtHBMEMxVo/JRf16auA6Yg5VwWYw4o+TYIiTE1vMcAORdEzoNjPDAz5M/0HQly+MvJPb9CR66tz4vmC/i00HJ2mBTRwXeEy5n4jpte/bFh21UIojn+wPe1wAyipq4m2faeUWCDQHyCd4ZCwvPQ9Wikajvz9joag1Te3yWnRtzHKct3U97KMLj+CqUQBj6hx9NF64QuAFVYBEWye1MYvBL+lgaoeDxusLZl1JgUUao5ZP+ihzIefh2fcti+TRBc94sQyTohgLr6bIbpIbBjVgnpPbiJ7e12607ZMyXNR/OoD4J2mMR8kMvzvmTYOMbCCJ9jYiogWMpbsyRGTDQRaYJAi8e56CkpLhpipbrYvSRGxLo=
  - secure: Hjs7ubq5MTPbNoD6/10ch56jKUJoV5CSEDzA0Hf8HjtQJAdMcb3BLxSxMf5kHGnbCTRMq90uadBMOoGR1Z44MvmBFIQDClhu8/LO29di4c7LvUOEdGZ7UjDM4BSCxJg4CGrHh6tZ0Hpj4MWkC9T96opYliunKMGMMz68fXJCum2qgGIQz7sFj/sBaq5S5HNygTtsSzfe39RAitJdHLyrSBbb8Pu6DQw7omfKJ4R3yV5lYspb6g+NtrOivIhNPOsyGnQZH7rz3S28NxuPAykkLhMNQJiKiGzaFaE0JaGcHcByVUp+NMA2CiVDMR5E5gAKRCKVSDp94mLMpw+Pl4wbMWPKw4LvQ+EOwq4qp07niIItvxoyJzHdY+KMJmZbWvIJhtyY/znNt/7MFsgFJs8BwE4rM9K6P5HJ1Y5roJWUDn8VKfyZ1RM9ib8NoEkgAXeyfwP/ucI8tzwbEY864sZ2wUbsak4CW9XAOJnSmwHWAMEAlZ7DL7tXOfdDWW+hm796JYL6aSLTJBhxJ3v+F4w/cV+wn7WAp+HOVl/OTY4xTWhoY1SMCh866A9fLztNxy14zo+Ue5m7u8m3przpUEX4fCLxt6kvOQDWtC9b9laK2QXbApKABOt/Mq+8VYufhAQspTGbysdDTxP1FrUrfVQrZpp2dSMSS3RNx8GVrP1Nu9E=
